### PR TITLE
Update 03-01-section-1.md

### PR DESCRIPTION
**Pull request by SteveMcMichael2022**
Hello, I've added some notes and youtube links that I've found helpful as a GRC hiring manager.  I've never contributed to a github project before.  I'm wide open to feedback on (1) whether you find this content helpful and (2) how it's presented.  I'm not sure how to make bullets and headings but attempted to copy what I see in other sections.

### CODE REVIEW

**Review by SteveMcMichael2022 — COMMENTED** [review]
Can someone please review these and approve or provide feedback?  Hope I'm navigating the process correctly and wide open to feedback as I try this.  Thanks.

**Review by marcmenninger — CHANGES_REQUESTED** [review]
Hi.

Thank you for your contribution. Please move it to be immediately after the Defining Your Team’s Culture section and before Unconventional Talent is Everywhere.

For the YouTube links, please create an inline link with the name of the video. See:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links

**Comment by SteveMcMichael2022** [comment]
> Hi.
> 
> Thank you for your contribution. Please move it to be immediately after the Defining Your Team’s Culture section and before Unconventional Talent is Everywhere.
> 
> For the YouTube links, please create an inline link with the name of the video. See:
> 
> https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links

Will do.  Even though it's a minor change I'm a bit stuck on how to navigate GitHub.  A developer colleague can help me in the next week or two.

**Review by KipBoyle — APPROVED** [review]
Excellent addition to the Handbook @SteveMcMichael2022 ! 

And, thanks for learning how to contribute through GitHub.

**Pull request merged**
